"""
fb_parser.py — Multilingual Facebook ad export HTML parser.

Parses HTML files exported from Facebook/Meta's "Download Your Information"
feature. Supports English, French, Portuguese, Spanish, Italian, German,
Dutch, Japanese, and Maltese exports.

Public API
----------
parse_html_content(filename, content) -> dict | None
    Returns {"file_type": str, "generated_by": str, "keywords": [str]}
    or None if the file is not a recognised Facebook export.
"""

from __future__ import annotations

import re
from typing import Optional

from bs4 import BeautifulSoup

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

# Substrings that must appear in the HTML to be considered a Facebook export.
HTML_REQUIRED_TOKENS = (
    "advertisers_using_your_activity_or_information",
    "your_activity_off_meta_technologies",
)

# File-type identifiers
FILE_TYPE_META_ACTIVITY = "META_ACTIVITY"
FILE_TYPE_ADVERTISER = "ADVERTISER"

# ---------------------------------------------------------------------------
# Multilingual detection phrases
# Each tuple: (off-meta phrase, advertiser phrase)
# ---------------------------------------------------------------------------
_DETECT_PHRASES: list[tuple[str, str]] = [
    # English
    (
        "your activity off meta technologies",
        "advertisers using your activity or information",
    ),
    # French
    (
        "votre activité en dehors des technologies meta",
        "annonceurs qui utilisent vos activités ou informations",
    ),
    # Portuguese
    (
        "atividade fora das tecnologias",
        "anunciantes que usam sua atividade",
    ),
    # Spanish
    (
        "tu actividad fuera de las tecnologías de meta",
        "anunciantes que utilizan tu actividad o información",
    ),
    # Japanese
    (
        "metaテクノロジー以外でのアクティビティ",
        "あなたのアクティビティや情報を利用している広告主",
    ),
    # Maltese
    (
        "l-attività tiegħek barra mit-teknoloġiji",
        "reklamaturi li jużaw l-attività jew l-informazzjoni tiegħek",
    ),
    # Italian
    (
        "la tua attività al di fuori delle tecnologie meta",
        "inserzionisti che utilizzano la tua attività o informazioni",
    ),
    # German
    (
        "deine aktivitäten außerhalb von meta-technologien",
        "werbetreibende, die deine aktivitäten oder informationen nutzen",
    ),
    # Dutch
    (
        "je activiteit buiten meta-technologieën",
        "adverteerders die je activiteit of informatie gebruiken",
    ),
]

# ---------------------------------------------------------------------------
# Multilingual "Generated by" patterns
# ---------------------------------------------------------------------------
_GENERATED_BY_PATTERNS: tuple[re.Pattern, ...] = (
    re.compile(r"Generated\s+by\s+(.+?)\s+on\b", re.I),                          # English
    re.compile(r"G\u00e9n\u00e9r\u00e9e?\s+par\s+(.+?)\s+le\b", re.I),          # French
    re.compile(r"Gera[dt][oa]\s+por\s+(.+?)\s+(?:em|a|no|na)\b", re.I),         # Portuguese
    re.compile(r"Generad[oa]\s+por\s+(.+?)\s+(?:el|en)\b", re.I),               # Spanish
    re.compile(r"Generat[oa]\s+da\s+(.+?)\s+(?:il|in|l')\b", re.I),             # Italian
    re.compile(r"Erstellt\s+von\s+(.+?)\s+am\b", re.I),                          # German
    re.compile(r"Gegenereerd\s+door\s+(.+?)\s+op\b", re.I),                      # Dutch
    re.compile(r"生成者[:\uff1a]\s*(.+?)(?:\s+\d|\s*$)", re.I),                    # Japanese (label)
    re.compile(r"(.+?)\s+によって生成", re.I),                                      # Japanese (passive)
    re.compile(                                                                    # Maltese
        r"I\u0121\u0121enerat[a]?\s+minn\s+(.+?)\s+(?:fl-|fit-|f'|fis-|fil-)\b",
        re.I,
    ),
)

# Pattern to extract domain from "Activity received from <domain>" spans in META_ACTIVITY files.
# Uses search (not match) and no end anchor so trailing content in nested elements doesn't break it.
_ACTIVITY_FROM_RE: re.Pattern = re.compile(
    r"activity\s+received\s+from\s+(\S+)", re.I
)

# Fallback: generic "generated by" verb variants for unsupported languages.
_FALLBACK_BY_VERBS: re.Pattern = re.compile(
    r"(?:generat\w*|erstellt|g[eé]n[eé]r[eé]\w*|gera[dt]\w*|gegenereerd)\s+"
    r"(?:by|par|por|von|door|da|minn)\s+(.+?)(?:\s+(?:on|le|em|am|op|il|fl-|fit-|f')\b|$)",
    re.I,
)

# Noise phrases to filter out of keyword/advertiser lists
_ADVERTISER_NOISE: frozenset[str] = frozenset(
    {
        "li 1",
        "li 2",
        "li 3",
        "a list uploaded by",
        "a custom audience",
        "x",
        "",
    }
)

# Generic Facebook section headings that are NOT company names
_FACEBOOK_SECTION_TITLES: frozenset[str] = frozenset(
    {
        "your activity off meta technologies",
        "votre activité en dehors des technologies meta",
        "atividade fora das tecnologias meta",
        "tu actividad fuera de las tecnologías de meta",
        "metaテクノロジー以外でのアクティビティ",
        "advertisers using your activity or information",
        "annonceurs qui utilisent vos activités ou informations",
        "anunciantes que usam sua atividade ou informações",
        "anunciantes que utilizan tu actividad o información",
        "あなたのアクティビティや情報を利用している広告主",
        "l-attività tiegħek barra mit-teknoloġiji",
        "la tua attività al di fuori delle tecnologie meta",
        "deine aktivitäten außerhalb von meta-technologien",
        "je activiteit buiten meta-technologieën",
        "apps and websites off of facebook",
        "off-facebook activity",
    }
)

# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------

_ENCODINGS = ("utf-8", "utf-8-sig", "latin-1", "iso-8859-1", "cp1252", "windows-1252")


def decode_bytes(data: bytes) -> str:
    """Decode raw bytes trying several encodings in order."""
    for enc in _ENCODINGS:
        try:
            return data.decode(enc)
        except (UnicodeDecodeError, LookupError):
            continue
    return data.decode("utf-8", errors="replace")


def _soup(html_text: str) -> BeautifulSoup:
    return BeautifulSoup(html_text, "html.parser")


def _is_facebook_export(text_lower: str) -> bool:
    """Return True if at least one required token appears in the lowercased HTML."""
    return any(tok in text_lower for tok in HTML_REQUIRED_TOKENS)


def detect_file_type(soup: BeautifulSoup, filename: str) -> Optional[str]:
    """
    Detect which Facebook export type the file represents.

    Returns FILE_TYPE_META_ACTIVITY, FILE_TYPE_ADVERTISER, or None.
    Filename is checked first; content is the fallback.
    """
    fname_lower = filename.lower()
    if "your_activity_off_meta_technologies" in fname_lower:
        return FILE_TYPE_META_ACTIVITY
    if "advertisers_using_your_activity_or_information" in fname_lower:
        return FILE_TYPE_ADVERTISER

    # Content fallback: look for detecting phrases
    body_text = soup.get_text(" ", strip=True).lower()
    for off_meta_phrase, advertiser_phrase in _DETECT_PHRASES:
        if off_meta_phrase in body_text:
            return FILE_TYPE_META_ACTIVITY
        if advertiser_phrase in body_text:
            return FILE_TYPE_ADVERTISER

    return None


def _extract_generated_by_from_text(text: str) -> Optional[str]:
    """Run all language patterns against *text* and return the first match."""
    for pat in _GENERATED_BY_PATTERNS:
        m = pat.search(text)
        if m:
            return m.group(1).strip()
    m = _FALLBACK_BY_VERBS.search(text)
    if m:
        return m.group(1).strip()
    return None


def extract_generated_by(soup: BeautifulSoup) -> Optional[str]:
    """
    Extract the "Generated by <company>" value from a parsed page.

    Tries the `_aoaa` container first (Facebook's typical wrapper), then
    falls back to scanning the full document text.
    """
    # Try scoped container
    container = soup.find(class_="_aoaa") or soup.find(class_="pam")
    if container:
        result = _extract_generated_by_from_text(container.get_text(" ", strip=True))
        if result:
            return result

    # Full document fallback
    return _extract_generated_by_from_text(soup.get_text(" ", strip=True))


def _is_noise(text: str) -> bool:
    """Return True if *text* should be excluded from the keyword list."""
    t = text.strip().lower()
    if t in _ADVERTISER_NOISE:
        return True
    if re.match(r"^li\s+\d+$", t):
        return True
    if t.startswith("a list uploaded"):
        return True
    if len(t) <= 1:
        return True
    return False


def _is_facebook_section_title(text: str) -> bool:
    """Return True if *text* is a generic Facebook section title (not a company name)."""
    return text.strip().lower() in _FACEBOOK_SECTION_TITLES


def _extract_company_from_heading(soup: BeautifulSoup) -> Optional[str]:
    """
    Extract company name from page heading for numbered sub-files.

    Tries Facebook-specific CSS classes first, then falls back to
    standard heading tags.
    """
    for cls in ("_a70d", "_a72m", "_a6-p"):
        el = soup.find(class_=cls)
        if el:
            text = el.get_text(" ", strip=True)
            if text and not _is_facebook_section_title(text) and not _is_noise(text):
                return text
    for tag in ("h1", "h2", "h3"):
        el = soup.find(tag)
        if el:
            text = el.get_text(" ", strip=True)
            if text and not _is_facebook_section_title(text) and not _is_noise(text):
                return text
    return None


def extract_keywords(soup: BeautifulSoup, file_type: str) -> list[str]:
    """
    Extract advertiser / company keyword names from the parsed page.

    For ADVERTISER files, uses CSS class selectors in order of specificity;
    div._2ph_._a6-p is the current Facebook export format for company names.
    For META_ACTIVITY files, extracts domain names from
    "Activity received from <domain>" span/div elements.
    Filters out generic Facebook section titles and noise strings.
    """
    keywords: list[str] = []

    if file_type == FILE_TYPE_ADVERTISER:
        # Advertiser names live in <div class="_2ph_ _a6-p"> in current export format.
        # Fall back through older/alternative class selectors as needed.
        for selector in ("div._2ph_._a6-p", "div._a6-g", "div._a72m", "div._a6_o", "li"):
            candidates = soup.select(selector)
            if candidates:
                for el in candidates:
                    text = el.get_text(" ", strip=True)
                    if text and not _is_noise(text) and not _is_facebook_section_title(text):
                        keywords.append(text)
                if keywords:
                    break

    elif file_type == FILE_TYPE_META_ACTIVITY:
        # Numbered sub-files contain off-site tracking events grouped by domain.
        # Extract the domain name from "Activity received from <domain>" elements.
        for el in soup.find_all(["span", "div"]):
            text = el.get_text(" ", strip=True)
            m = _ACTIVITY_FROM_RE.search(text)
            if m:
                domain = m.group(1).strip().rstrip(".")
                if domain and not _is_noise(domain):
                    keywords.append(domain)
        # Secondary: parent/index file (your_activity_off_meta_technologies.html) stores
        # company names in <section class="_a6-g"><h2><a> elements — no "Activity received
        # from" spans exist there, so the loop above yields nothing.
        # Company name h2s contain <a> links to sub-files; page section headers do not.
        if not keywords:
            for a_el in soup.select("section._a6-g h2 a"):
                text = a_el.get_text(" ", strip=True)
                if text and not _is_noise(text) and not _is_facebook_section_title(text):
                    keywords.append(text)
            # Fallback: h2 without anchor link (older export formats).
            # Skip any text containing "Generated by" to avoid picking up page headers.
            if not keywords:
                for h2 in soup.select("section._a6-g h2"):
                    text = h2.get_text(" ", strip=True)
                    if (text
                            and not _is_noise(text)
                            and not _is_facebook_section_title(text)
                            and "generated by" not in text.lower()):
                        keywords.append(text)

    # De-duplicate while preserving order
    seen: set[str] = set()
    unique: list[str] = []
    for kw in keywords:
        key = kw.lower()
        if key not in seen:
            seen.add(key)
            unique.append(kw)

    return unique


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def parse_html_content(
    filename: str,
    content: str | bytes,
) -> Optional[dict]:
    """
    Parse a Facebook HTML export file.

    Parameters
    ----------
    filename : str
        Original filename (used for file-type detection).
    content : str | bytes
        Raw HTML content.

    Returns
    -------
    dict with keys:
        "file_type"   — FILE_TYPE_META_ACTIVITY | FILE_TYPE_ADVERTISER
        "generated_by" — company/advertiser name string (may be empty)
        "keywords"    — list of advertiser keyword strings
    or None if the file is not a recognised Facebook export.
    """
    if isinstance(content, bytes):
        content = decode_bytes(content)

    # Quick rejection before parsing — check filename/path first, then content
    text_lower = content.lower()
    fname_lower = filename.lower()
    if not (any(tok in fname_lower for tok in HTML_REQUIRED_TOKENS) or _is_facebook_export(text_lower)):
        return None

    soup = _soup(content)

    file_type = detect_file_type(soup, filename)
    if file_type is None:
        return None

    generated_by = extract_generated_by(soup) or ""
    keywords = extract_keywords(soup, file_type)

    # Fallback for META_ACTIVITY sub-files when no "Activity received from" text found.
    # Two cases:
    #   1. Pure-digit stem (e.g. 0.html, 497.html) → extract company from page heading.
    #   2. Named stem (e.g. peacocktv_201535953800378100.html) → strip _<digits> suffix.
    if not keywords and file_type == FILE_TYPE_META_ACTIVITY:
        fname_base = filename.rsplit("/", 1)[-1]
        stem = fname_base.rsplit(".", 1)[0]
        if stem.isdigit():
            company = _extract_company_from_heading(soup)
            if company:
                keywords = [company]
        else:
            m = re.match(r"^(.+?)_\d+$", stem)
            if m:
                domain = m.group(1).strip()
                if domain and not _is_noise(domain) and not _is_facebook_section_title(domain):
                    keywords = [domain]
            else:
                # Named stem with no _<digits> suffix (e.g. "facebook.html").
                # Try heading extraction first; fall back to the stem itself.
                company = _extract_company_from_heading(soup)
                if company:
                    keywords = [company]
                elif stem and not _is_noise(stem) and not _is_facebook_section_title(stem):
                    keywords = [stem]

    return {
        "file_type": file_type,
        "generated_by": generated_by,
        "keywords": keywords,
    }
